place_Discourse_sidebar:
  type: enum
  default: left (default)
  choices:
    - right

#header_transparency:
#  type: float
#  default: 0.60

header_blur_px:
  type: integer
  default: 5

topic_pop_amount:
  type: float
  default: 1.1

topic_pop_duration:
  type: float
  default: 0.2
