place_Discourse_sidebar:
  type: enum
  default: left (default)
  choices:
    - right

# Error: $alpha: 0.6 is not a number. ╷ 6 │ background-color: rgba(255, 255, 255, $header_transparency); │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ╵ /var/www/discourse/common.scss 6:21 root stylesheet
# header_transparency:
#   type: float
#   default: 0.6
#   max: 1.0
#   min: 0

header_blur_px:
  type: integer
  default: 5
  min: 0

topic_pop_amount:
  type: float
  default: 1.1
  max: 10.0
  min: 0

topic_pop_duration:
  type: float
  default: 0.2
  max: 10.0
  min: 0
